plugins:
  - removeStyleElement: true
  - removeDimensions: true
  - cleanupIDs: false
  - removeUnknownsAndDefaults:
      SVGid: false
  - removeAttrs:
      attrs:
        - 'path:class'
        - 'path:fill-rule'
        - 'path:clip-rule'
