sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 8
notifications:
  email: false
script:
  - npm run lint
  - npm run test:coverage
deploy:
  - provider: script
    skip_cleanup: true
    script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    on:
      all_branches: true
      master: false
  - provider: script
    skip_cleanup: true
    script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    on:
      master: true
