sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 8
notifications:
  email: false
script:
  - npm run validate
deploy:
  provider: script
  script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
  on:
    master: true