// flow-typed signature: 42a3be9283fab92ad04fa697f5fadf71
// flow-typed version: <<STUB>>/gulp-svg-sprite_v^1.3.6/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-svg-sprite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-svg-sprite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-svg-sprite/index' {
  declare module.exports: $Exports<'gulp-svg-sprite'>;
}
declare module 'gulp-svg-sprite/index.js' {
  declare module.exports: $Exports<'gulp-svg-sprite'>;
}
