// flow-typed signature: 6ee17939fa4053c22046585b091b6f35
// flow-typed version: <<STUB>>/synbydesign.design_v^0.3.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'synbydesign.design'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'synbydesign.design' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'synbydesign.design/src/index' {
  declare module.exports: any;
}

declare module 'synbydesign.design/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'synbydesign.design/src/index.js' {
  declare module.exports: $Exports<'synbydesign.design/src/index'>;
}
declare module 'synbydesign.design/webpack.config.js' {
  declare module.exports: $Exports<'synbydesign.design/webpack.config'>;
}
