name: After server responds
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn build:common-ui && yarn workspace @synbydesign/website start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 300
          browser: chrome
          headless: true
