name: Unit Tests
on: push
jobs:
  unit tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Lint Scripts
        run: npm run lint:script
      - name: Lint Styles
        run: npm run lint:style
      - name: Type Check
        run: npm run type-check
      - name: Run tests
        run: npm run test
